# Generated by Django 5.0.7 on 2024-07-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
