# Generated by Django 5.0.7 on 2024-07-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_consulta_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Questions',
        ),
    ]
